### PR TITLE
Fix for #120. Rename jakarta-commons-logging to apache-commons-loggin…

### PR DESCRIPTION
**Pull request by sbaryakov**
…g in centos7

### CODE REVIEW

**Comment by mcanevet** [comment]
@sbaryakov please fix lint tests.

**Comment by sbaryakov** [comment]
any chance to get this one merged ?

**Comment by mcanevet** [comment]
@sbaryakov could you please rebase so that acceptance tests runs on Travis CI?

**Comment by mcanevet** [comment]
@sbaryakov thanks

**Pull request merged**
